; PlatformIO Project Configuration File
; Analyseur O2 portable - Arduino Nano (ATmega328P)

[env:nanoatmega328new]
platform  = atmelavr
board     = nanoatmega328new   ; Nano avec bootloader optiboot (le plus courant aujourd'hui)
framework = arduino
monitor_speed = 9600
upload_speed  = 115200

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/RTClib @ ^2.1.4
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    adafruit/Adafruit PN532 @ ^1.3.0
    adafruit/Adafruit NeoPixel @ ^1.12.0

build_flags =
    -Wall
    -Wextra

; Si ta carte refuse de flasher (erreur avrdude stk500), bascule sur l'env
; ci-dessous avec l'ancien bootloader :
[env:nanoatmega328]
platform  = atmelavr
board     = nanoatmega328
framework = arduino
monitor_speed = 9600
upload_speed  = 57600

lib_deps   = ${env:nanoatmega328new.lib_deps}
build_flags = ${env:nanoatmega328new.build_flags}
